[ -z "$PS1" ] && return

[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
[ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ] && . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"

export HISTCONTROL=ignoreboth
export HISTSIZE=5000
export HISTFILESIZE=5000
export LC_CTYPE=en_US.UTF-8
export CLICOLOR=1

PS1='\[\e[34;1m\]\t \[\e[33;1m\][\h \[\e[37;1m\]\W\[\e[33;1m\]] \[\e[31;1m\]\$ \[\e[0m\]'
